# fly.toml app configuration file generated for potterblog-preview on 2024-03-14T09:39:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'potterblog'
primary_region = 'den'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512mb"

[[statics]]
  guest_path = '/usr/build/public/images'
  url_prefix = '/images'

[[statics]]
  guest_path = '/usr/build/public/videos'
  url_prefix = '/videos'

[[statics]]
  guest_path = '/usr/build/public/fonts'
  url_prefix = '/fonts'

[[statics]]
  guest_path = '/usr/build/public/icons'
  url_prefix = '/icons'

[[statics]]
  guest_path = '/usr/build/.next/static'
  url_prefix = '/_next/static'
