name: Build Container Image
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: redhat-actions/buildah-build@v2
      with:
        image: site
        containerfiles: |
          Containerfile
